server {
    listen 80;
    server_name 13.127.58.137;
    location / {
        proxy_pass https://amzn-frontend-ebad.s3.ap-south-1.amazonaws.com;
        proxy_set_header Host amzn-frontend-ebad.s3.ap-south-1.amazonaws.com;

        proxy_set_header Authorization "";
        proxy_hide_header x-amz-id-2;
        proxy_hide_header x-amz-request-id;

        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }
    location /api/ {
        proxy_pass http://127.0.0.1:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}